devtool/rfstool: move common functions to shared lib.
The following are shared between devtool and rfstool and,
as requested by PR feedback, have been moved to a common lib

  - all error handling functions
  - ensure_docker
  - get_user_confirmation
  - ensure_build_dir
  - ensure_(dev|rfs)ctr -> and renamed to ensure_ctr
  - run_(dev|rfs)ctr -> and renamed to run_ctr
  - cmd_shell
  - main

Also tidied up the package variables and added unattended option
and shell function back into rfstool.

Signed-off-by: Fraser Pringle <fraser.pringle@gmail.com>

diff --git a/tools/devtool b/tools/devtool
--- a/tools/devtool
+++ b/tools/devtool
@@ -73,7 +73,7 @@
 # Development container image (name:tag)
 # This should be updated whenever we upgrade the development container.
 # (Yet another step on our way to reproducible builds.)
-DEVCTR_IMAGE="fcuvm/dev:v14"
+CTR_IMAGE="fcuvm/dev:v14"
 
 # Naming things is hard
 MY_NAME="Firecracker $(basename "$0")"
@@ -118,97 +118,16 @@ CTR_MICROVM_IMAGES_DIR="$CTR_FC_BUILD_DIR/img"
 # These options are not command-specific, so we store them as global vars
 OPT_UNATTENDED=false
 
-
-# Send a decorated message to stdout, followed by a new line
+# Load common functions
 #
-say() {
-    [ -t 1 ] && [ -n "$TERM" ] \
-        && echo "$(tput setaf 2)[$MY_NAME]$(tput sgr0) $*" \
-        || echo "[$MY_NAME] $*"
-}
+if [[ ! -f "${FC_TOOLS_DIR}/functions" ]]; then
+   echo "Unable to find ${FC_TOOLS_DIR}/functions lib.  Aborting."
+   exit 1
+else
+   source "${FC_TOOLS_DIR}/functions"
+fi
 
-# Send a decorated message to stdout, without a trailing new line
-#
-say_noln() {
-    [ -t 1 ] && [ -n "$TERM" ] \
-        && echo -n "$(tput setaf 2)[$MY_NAME]$(tput sgr0) $*" \
-        || echo "[$MY_NAME] $*"
-}
 
-# Send a text message to stderr
-#
-say_err() {
-    [ -t 2 ] && [ -n "$TERM" ] \
-        && echo "$(tput setaf 1)[$MY_NAME] $*$(tput sgr0)" 1>&2 \
-        || echo "[$MY_NAME] $*" 1>&2
-}
-
-# Send a warning-highlighted text to stdout
-say_warn() {
-    [ -t 1 ] && [ -n "$TERM" ] \
-        && echo "$(tput setaf 3)[$MY_NAME] $*$(tput sgr0)" \
-        || echo "[$MY_NAME] $*"
-}
-
-# Exit with an error message and (optional) code
-# Usage: die [-c <error code>] <error message>
-#
-die() {
-    code=1
-    [[ "$1" = "-c" ]] && {
-        code="$2"
-        shift 2
-    }
-    say_err "$@"
-    exit $code
-}
-
-# Exit with an error message if the last exit code is not 0
-#
-ok_or_die() {
-    code=$?
-    [[ $code -eq 0 ]] || die -c $code "$@"
-}
-
-# Check if Docker is available and exit if it's not.
-# Upon returning from this call, the caller can be certain Docker is available.
-#
-ensure_docker() {
-    NEWLINE=$'\n'
-    output=$(which docker 2>&1)
-    ok_or_die "Docker not found. Aborting." \
-        "Please make sure you have Docker (http://docker.com) installed" \
-        "and properly configured.${NEWLINE}" \
-        "Error: $?, command output: ${output}"
-
-    output=$(docker ps 2>&1)
-    ok_or_die "Error accessing Docker. Please make sure the Docker daemon" \
-        "is running and that you are part of the docker group.${NEWLINE}" \
-        "Error: $?, command output: ${output}${NEWLINE}" \
-        "For more information, see" \
-        "https://docs.docker.com/install/linux/linux-postinstall/"
-}
-
-# Attempt to download our Docker image. Exit if that fails.
-# Upon returning from this call, the caller can be certain our Docker image is
-# available on this system.
-#
-ensure_devctr() {
-
-    # We depend on having Docker present.
-    ensure_docker
-
-    # Check if we have the container image available locally. Attempt to
-    # download it, if we don't.
-    [[ $(docker images -q "$DEVCTR_IMAGE" | wc -l) -gt 0 ]] || {
-        say "About to pull docker image $DEVCTR_IMAGE"
-        get_user_confirmation || die "Aborted."
-
-        docker pull "${DEVCTR_IMAGE}"
-
-        ok_or_die "Error pulling docker image. Aborting."
-    }
-}
 
 # Check if /dev/kvm exists. Exit if it doesn't.
 # Upon returning from this call, the caller can be certain /dev/kvm is
@@ -216,22 +135,6 @@ ensure_devctr() {
 #
 ensure_kvm() {
     [[ -c /dev/kvm ]] || die "/dev/kvm not found. Aborting."
-}
-
-# Make sure the build/ dirs are available. Exit if we can't create them.
-# Upon returning from this call, the caller can be certain the build/ dirs exist.
-#
-ensure_build_dir() {
-    for dir in "$FC_BUILD_DIR" "$CARGO_TARGET_DIR" \
-               "$CARGO_REGISTRY_DIR" "$CARGO_GIT_REGISTRY_DIR"; do
-        mkdir -p "$dir" || die "Error: cannot create dir $dir"
-        [ -x "$dir" ] && [ -w "$dir" ] || \
-            {
-                say "Wrong permissions for $dir. Attempting to fix them ..."
-                chmod +x+w "$dir"
-            } || \
-            die "Error: wrong permissions for $dir. Should be +x+w"
-    done
 }
 
 # Fix build/ dir permissions after a privileged container run.
@@ -242,37 +145,11 @@ ensure_build_dir() {
 fix_build_dir_perms() {
     # Yes, running Docker to get elevated privileges, just to chown some files
     # is a dirty hack.
-    run_devctr \
+    run_ctr \
         -- \
         chown -R "$(id -u):$(id -g)" "$CTR_FC_BUILD_DIR"
 }
 
-# Prompt the user for confirmation before proceeding.
-# Args:
-#   $1  prompt text.
-#       Default: Continue? (y/n)
-#   $2  confirmation input.
-#       Default: y
-# Return:
-#   exit code 0 for successful confirmation
-#   exit code != 0 if the user declined
-#
-get_user_confirmation() {
-
-    # Pass if running unattended
-    [[ "$OPT_UNATTENDED" = true ]] && return 0
-
-    # Fail if STDIN is not a terminal (there's no user to confirm anything)
-    [[ -t 0 ]] || return 1
-
-    # Otherwise, ask the user
-    #
-    msg=$([ -n "$1" ] && echo -n "$1" || echo -n "Continue? (y/n) ")
-    yes=$([ -n "$2" ] && echo -n "$2" || echo -n "y")
-    say_noln "$msg"
-    read c && [ "$c" = "$yes" ] && return 0
-    return 1
-}
 
 # Validate the user supplied version number.
 # It must be composed of 3 groups of integers separated by dot.
@@ -320,47 +197,7 @@ compose_tag_text() {
       | sed "s/^###\s//g"
 }
 
-# Helper function to run the dev container.
-# Usage: run_devctr <docker args> -- <container args>
-# Example: run_devctr --privileged -- bash -c "echo 'hello world'"
-run_devctr() {
-    docker_args=()
-    ctr_args=()
-    docker_args_done=false
-    while [[ $# -gt 0 ]]; do
-        [[ "$1" = "--" ]] && {
-            docker_args_done=true
-            shift
-            continue
-        }
-        [[ $docker_args_done = true ]] && ctr_args+=("$1") || docker_args+=("$1")
-        shift
-    done
 
-    # If we're running in a terminal, pass the terminal to Docker and run
-    # the container interactively
-    [[ -t 0 ]] && docker_args+=("-i")
-    [[ -t 1 ]] && docker_args+=("-t")
-
-    # Try to pass these environments from host into container for network proxies
-    proxies=(http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY)
-    for i in "${proxies[@]}"; do
-        if [[ ! -z ${!i} ]]; then
-            docker_args+=("--env") && docker_args+=("$i=${!i}")
-        fi
-    done
-
-    # Finally, run the dev container
-    # Use 'z' on the --volume parameter for docker to automatically relabel the
-    # content and allow sharing between containers.
-    docker run "${docker_args[@]}" \
-        --rm \
-        --volume /dev:/dev \
-        --volume "$FC_ROOT_DIR:$CTR_FC_ROOT_DIR:z" \
-        --env OPT_LOCAL_IMAGES_PATH="$(dirname "$CTR_MICROVM_IMAGES_DIR")" \
-        --env PYTHONDONTWRITEBYTECODE=1 \
-        "$DEVCTR_IMAGE" "${ctr_args[@]}"
-}
 
 # `$0 help`
 # Show the detailed devtool usage information.
@@ -450,7 +287,7 @@ cmd_build() {
     target="$(uname -m)-unknown-linux-${libc}"
 
     # Check prerequisites
-    ensure_devctr
+    ensure_ctr
     ensure_build_dir
 
     say "Starting build ($profile, $libc) ..."
@@ -481,7 +318,7 @@ cmd_build() {
     #
     # Note: we need to pass an explicit TARGET_CC to cargo, because the `cc`
     # crate gets confused for aarch64 musl.
-    run_devctr \
+    run_ctr \
         --user "$(id -u):$(id -g)" \
         --workdir "$CTR_FC_ROOT_DIR" \
         --env TARGET_CC=musl-gcc \
@@ -521,9 +358,8 @@ cmd_test() {
 
     # Check prerequisites.
     ensure_kvm
-    ensure_devctr
+    ensure_ctr
     ensure_build_dir
-
 
     # If we got to here, we've got all we need to continue.
     say "Starting test run ..."
@@ -532,7 +368,7 @@ cmd_test() {
     # in order to set-up the Firecracker jail (manipulating cgroups, net
     # namespaces, etc).
     # We need to run a privileged container to get that kind of access.
-    run_devctr \
+    run_ctr \
         --privileged \
         --security-opt seccomp=unconfined \
         --ulimit core=0 \
@@ -548,74 +384,6 @@ cmd_test() {
 
     return $ret
 }
-
-# `$0 shell` - drop to a shell prompt inside the dev container
-# Please see `$0 help` for more information.
-#
-cmd_shell() {
-
-    # By default, we run the container as the current user.
-    privileged=false
-
-    # Parse any command line args.
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            "-h"|"--help")          { cmd_help; exit 1; } ;;
-            "-p"|"--privileged")    { privileged=true;  } ;;
-            *)
-                die "Unknown argument: $1. Please use --help for help."
-            ;;
-        esac
-        shift
-    done
-
-    # Make sure we have what we need to continue.
-    ensure_devctr
-    ensure_build_dir
-
-    if [[ $privileged = true ]]; then
-        # If requested, spin up a privileged container.
-        #
-        say "Dropping to a privileged shell prompt ..."
-        say "Note: $FC_ROOT_DIR is bind-mounted under $CTR_FC_ROOT_DIR"
-        say_warn "You are running as root; any files that get created under" \
-            "$CTR_FC_ROOT_DIR will be owned by root."
-        run_devctr \
-            --privileged \
-            --security-opt seccomp=unconfined \
-            --workdir "$CTR_FC_ROOT_DIR" \
-            -- \
-            bash
-        ret=$?
-
-        # Running as root may have created some root-owned files under the build
-        # dir. Let's fix that.
-        #
-        fix_build_dir_perms
-    else
-        say "Dropping to shell prompt as user $(whoami) ..."
-        say "Note: $FC_ROOT_DIR is bind-mounted under $CTR_FC_ROOT_DIR"
-        say_warn "You won't be able to run Firecracker via the jailer," \
-            "but you can still build it."
-        say "You can use \`$0 shell --privileged\` to get a root shell."
-
-        [ -w /dev/kvm ] || \
-            say_warn "WARNING: user $(whoami) doesn't have permission to" \
-                "access /dev/kvm. You won't be able to run Firecracker."
-
-        run_devctr \
-            --user "$(id -u):$(id -g)" \
-            --device=/dev/kvm:/dev/kvm \
-            --workdir "$CTR_FC_ROOT_DIR" \
-            --env PS1="$(whoami)@\h:\w\$ " \
-            -- \
-            bash --norc
-        ret=$?
-    fi
-
-    return $ret
-}
-
 
 # Auto-format all source code, to match the Firecracker requirements. For the
 # moment, this is just a wrapper over `cargo fmt --all`
@@ -634,10 +402,10 @@ cmd_fmt() {
         shift
     done
 
-    ensure_devctr
+    ensure_ctr
 
     say "Applying rustfmt ..."
-    run_devctr \
+    run_ctr \
         --user "$(id -u):$(id -g)" \
         --workdir "$CTR_FC_ROOT_DIR" \
         -- \
@@ -663,7 +431,7 @@ cmd_prepare_release() {
     validate_version "$version"
 
     # We'll be needing the dev container later on.
-    ensure_devctr
+    ensure_ctr
 
     # The cargo registry dir needs to be there for `cargo update`.
     ensure_build_dir
@@ -689,7 +457,7 @@ cmd_prepare_release() {
 
     # Update crate dependencies.
     say "Updating crate dependencies..."
-    run_devctr \
+    run_ctr \
         --user "$(id -u):$(id -g)" \
         --workdir "$CTR_FC_ROOT_DIR" \
         -- \
@@ -854,42 +622,6 @@ cmd_checkenv() {
     check_L1TF
     check_SMT
     check_swap
-}
-
-main() {
-
-    if [ $# = 0 ]; then
-	die "No command provided. Please use \`$0 help\` for help."
-    fi
-
-    # Parse main command line args.
-    #
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            -h|--help)              { cmd_help; exit 1;     } ;;
-            -y|--unattended)        { OPT_UNATTENDED=true;  } ;;
-            -*)
-                die "Unknown arg: $1. Please use \`$0 help\` for help."
-            ;;
-            *)
-                break
-            ;;
-        esac
-        shift
-    done
-
-    # $1 is now a command name. Check if it is a valid command and, if so,
-    # run it.
-    #
-    declare -f "cmd_$1" > /dev/null
-    ok_or_die "Unknown command: $1. Please use \`$0 help\` for help."
-
-    cmd=cmd_$1
-    shift
-
-    # $@ is now a list of command-specific args
-    #
-    $cmd "$@"
 }
 
 main "$@"
