devtool: script for automatic release drafting
Signed-off-by: Diana Popa <dpopa@amazon.com>

diff --git a/tools/devtool b/tools/devtool
--- a/tools/devtool
+++ b/tools/devtool
@@ -396,6 +396,35 @@ validate_version() {
 
 }
 
+# Validate that the repo targetted for a release exists.
+#
+validate_repo() {
+    user="$1"
+    repo="$2"
+    if [ -z "$user" ]; then
+        die "GitHub user cannot be empty."
+    fi
+    git_link="https://api.github.com/repos/$user/$repo"
+    status_code=$(curl --write-out %{http_code} --silent --output /dev/null $git_link)
+    if [[ "$status_code" -ne 200 ]] ; then
+        die "GitHub repo $git_link is not valid. Please provide a valid user/org and repository."
+    fi
+}
+
+# Validate there is no tag currently associated with the version provided.
+#
+check_release_tag() {
+    say "Fetching remote tags..."
+    git fetch upstream --tags
+
+    if git rev-parse v$1 >/dev/null 2>&1; then
+        say_err "Seems that tag provided is already associated with a release! "
+        say "Will skip drafting a new release for now."
+        return 1
+    fi
+    return 0
+}
+
 # Validate the user supplied kernel version number.
 # It must be composed of 2 groups of integers separated by dot, with an optional third group.
 validate_kernel_version() {
@@ -411,34 +440,116 @@ validate_kernel_version() {
 }
 
 # Compose the text for a new release tag using the information in the changelog,
-# between the two specified releases.
-# The following transformations are applied:
-# * `-` is replaced with `*` for unnumbered lists.
-# * section headers (`###`) are removed.
-#
+# between the two specified releases. Section headers (`###`) are removed.
 # Args:
 #   $1  previous version.
 #   $2  new version.
 #
 compose_tag_text() {
-    declare prev_ver="$1"
-    declare curr_ver="$2"
+    release_text=$(compose_release_text "$1" "$2") || die "Could not compose release description."
+    echo "$release_text" | sed "s/^###\s//g"
+}
+
+# Compose the text for a new release using the information in the changelog,
+# between the two specified releases.
+# Args:
+#   $1  previous version.
+#   $2  new version.
+#
+compose_release_text() {
+    declare curr_ver="$1"
+    declare prev_ver="$2"
     declare changelog="$FC_ROOT_DIR/CHANGELOG.md"
 
-    validate_version "$prev_ver"
-    validate_version "$curr_ver"
-
     # Patterns for the sections in the changelog corresponding to the versions.
-    pat_prev="^##\s\[$prev_ver\]"
     pat_curr="^##\s\[$curr_ver\]"
-
+    pat_prev="^##\s\[$prev_ver\]"
     # Extract the section enclosed between the 2 headers and strip off the first
     # 2 and last 2 lines (one is blank and one contains the header `## [A.B.C]`).
     # Then, replace `-` with `*` and remove section headers.
     sed "/$pat_curr/,/$pat_prev/!d" "$changelog" \
       | sed '1,2d;$d' \
-      | sed "s/^-/*/g" \
-      | sed "s/^###\s//g"
+      | sed "s/^-/*/g"
+}
+
+get_prev_release() {
+    declare version=$1
+    declare pat_release="^## \[([0-9]+\.){2}[0-9]+\]"
+    declare changelog="$FC_ROOT_DIR/CHANGELOG.md"
+
+    grep -q "\[$version\]" "$changelog"
+    ok_or_die "No changelog entry for release $version can be found. Make sure you have run ./devtool prepare_release."
+    # We work with the assumption that the changelog has already been updated
+    # and contains a header (and a corresponding section) for the new release.
+
+    # Step 1: Get all release numbers.
+    all_releases=($(grep -E "$pat_release" "$changelog"))
+    # Step 2: Trim out headers (`##`).
+    all_releases=(${all_releases[@]//##*})
+
+    # Step 3: Walk the array until we come across the desired release number,
+    # then pick up the next one. Since the latest releases are at the top of the
+    # changelog, the next one in line will be the previous one chronologically.
+    # The array now contains all the release numbers in the changelog, enclosed
+    # in square brackets.
+    for release in "${all_releases[@]}"; do
+        if [ -n "$found" ]; then
+            # Trim out square brackets.
+            prev_version=$(echo "$release" | awk -F"[][]" "{print \$2}")
+            break
+        elif [ "$release" == "[$version]" ]; then
+            found=1
+        fi
+    done
+
+    if [ -z "$prev_version" ]; then
+        die "Could not find a previous release for v$version."
+    fi
+
+    echo $prev_version
+}
+
+# Auxiliary function for creating the JSON for calling into
+# GitHub's API for posting a release.
+generate_release_post_data() {
+  cat <<EOF
+{
+  "tag_name": "v$1",
+  "target_commitish": "$2",
+  "name": "Firecracker v$1",
+  "body": "$4",
+  "draft": $draft,
+  "prerelease": $3
+}
+EOF
+}
+
+# Call into GitHub's API to draft a release.
+post_release() {
+    version="$1"
+    branch="$2"
+    user="$3"
+    repo="$4"
+    token="$5"
+    prerelease="$6"
+    release_text="$7"
+    # Will always create a draft release.
+    draft="true"
+
+    # We need to replace the newlines from the changelog content with
+    # literal newlines (i.e \n).
+    # Second pass: escape quotation marks.
+    json_changelog_content=$(echo "$release_text" | awk '{printf "%s\\n", $0}' | sed 's/\"/\\"/g')
+    API_JSON="$(generate_release_post_data $version $branch $prerelease "$json_changelog_content")"
+    API_RESPONSE_STATUS=$(curl -H "Authorization: token $token" --data "$API_JSON" -s -i https://api.github.com/repos/$3/$4/releases)
+
+    if [[ ! "$API_RESPONSE_STATUS" == *"HTTP/2 201"* ]]; then
+        die "Could not post release: $API_RESPONSE_STATUS"
+    fi
+}
+
+get_branch() {
+    echo `git rev-parse --abbrev-ref HEAD`
 }
 
 # Helper function to run the dev container.
@@ -588,6 +699,10 @@ cmd_help() {
     echo "        Prepare a new Firecracker release by updating the version number, crate "
     echo "        dependencies and credits."
     echo ""
+
+    help_release
+
+    echo ""
     echo "    shell [--privileged]"
     echo "        Launch the development container and open an interactive BASH shell."
     echo "        -p, --privileged    Run the container as root, in privileged mode."
@@ -614,6 +729,22 @@ cmd_help() {
     echo "    strip"
     echo "        Strip debug symbols from the Firecracker release binaries."
     echo ""
+}
+
+help_release() {
+    echo "    release -v <val> -u <val> [-t <val> -r <val> -m <val> -p]"
+    echo "        Draft a GitHub release by calling into its API."
+    echo "        Firstly, a tag will be created for the release number provided, together with a"
+    echo "        description obtained from the CHANGELOG file. The tag will be pushed to a provided remote."
+    echo "        Secondly, the script will call into GitHub's API for programatically posting a draft release."
+    echo "        For authentication reasons, one needs to pass a GitHub API access token."
+    echo "        You can find instructions on how to create one: https://github.blog/2013-05-16-personal-api-tokens/."
+    echo "        -v, --version             The targeted release version."
+    echo "        -u, --username            The GitHub owner of the targeted repo."
+    echo "        -t, --token               A GitHub Access token with "repo" permissions"
+    echo "        -r, --repo                The name of the repository where the release will be posted."
+    echo "        -m, --remote              The name of the remote where the release tag will be pushed."
+    echo "        -p, --prerelease          Marks the release as a pre-release."
 }
 
 # `$0 build` - build Firecracker
@@ -1092,69 +1223,133 @@ cmd_prepare_release() {
     rm -f "$FC_ROOT_DIR/CHANGELOG.md="
 }
 
-# Create a tag for the specified release.
-# The tag text will be composed from the changelog contents enclosed between the
-# specified release number and the previous one.
-# Args:
-#   $1  release number.
-# Example: `devtool tag 0.42.0`
+# Publish a Firecracker draft release to GitHub.
+# For this one needs to pass a GitHub API access token.
+# You can find instructions on how to create one: https://github.blog/2013-05-16-personal-api-tokens/.
+# If the tag associated with the intended release already exists or if the user has not specified
+# a GitHub API token, the script exits.
+# Example: `devtool release -v 0.42.0 -b main -t token`
 #
-cmd_tag() {
+cmd_release() {
+    local prerelease="false"
+    local repo="firecracker"
+    local remote="origin"
 
     # Parse any command line args.
     while [ $# -gt 0 ]; do
         case "$1" in
-            "-h"|"--help")      { cmd_help; exit 1;    } ;;
-            *)                  { version="$1"; break; } ;;
+            "-h"|"--help")      { help_release; exit 1; } ;;
+            "-v"|"--version")
+                shift
+                local version="$1"
+                ;;
+            "-t"|"--token")
+                shift
+                local token="$1"
+                ;;
+             "-u"|"--username")
+                shift
+                local user="$1"
+                ;;
+              "-r"|"--repo")
+                shift
+                repo="$1"
+                ;;
+              "-m"|"--remote")
+                shift
+                remote="$1"
+                ;;
+              "-p"|"--prerelease")
+                shift
+                prerelease="true"
+                ;;
+            *)
+                die "Unknown argument: $1. Please use --help for help."
+            ;;
         esac
         shift
     done
 
     validate_version "$version"
+    validate_repo "$user" "$repo"
 
-    declare pat_release="^## \[([0-9]+\.){2}[0-9]+\]"
-    declare changelog="$FC_ROOT_DIR/CHANGELOG.md"
+    # Obtain the current branch.
+    branch=$(get_branch)
+    say "Will start creating a draft release for branch $branch ..."
+    get_user_confirmation || die "Aborted."
 
-    grep -q "\[$version\]" "$changelog"
-    ok_or_die "No changelog entry for release $version can be found."
+    # Check that the release tag associated with the provided version
+    # does not already exist. If the tag exists, we will not try to
+    # post a release on GitHub.
+    check_release_tag "$version" || skip_github_release=true
 
-    # We work with the assumption that the changelog has already been updated
-    # and contains a header (and a corresponding section) for the new release.
+    if [[ -z "$skip_github_release" ]]; then
+        if [[ -z "$token" ]]; then
+            say_err "In order to draft a GitHub release you need to pass a Github API Access Token!"
+        else
+            prev_ver=$(get_prev_release "$version") || die "Could not obtain previous release version."
 
-    # Step 1: Get all release numbers.
-    all_releases=($(grep -E "$pat_release" "$changelog"))
+            # Start by creating a local tag and associate to it a description.
+            say "Creating local tag..."
+            create_local_tag "$version" "$prev_ver" || die "Could not create local tag v"$version"."
 
-    # Step 2: Trim out headers (`##`).
-    all_releases=(${all_releases[@]//##*})
+            # From now on, any function that will fail will also need to revert creation of local tag.
+            say "Continue with remote tag push?"
+            get_user_confirmation || die "Local tag not pushed to remote "$remote"."
+            push_local_tag "$version" "$remote" || delete_local_tag "$version" "Failed to push local tag v"$version"."
 
-    # Step 3: Walk the array until we come across the desired release number,
-    # then pick up the next one. Since the latest releases are at the top of the
-    # changelog, the next one in line will be the previous one chronologically.
-    # The array now contains all the release numbers in the changelog, enclosed
-    # in square brackets.
-    found=
-    for release in "${all_releases[@]}"; do
-        if [ ! -z "$found" ]; then
-            # Trim out square brackets.
-            prev_version=$(echo "$release" | awk -F"[][]" "{print \$2}")
-            break
-        elif [ "$release" == "[$version]" ]; then
-            found=1
-        fi
-    done
+            say "Continue with posting a GitHub Release?"
+            get_user_confirmation || delete_remote_tag "$version" "$remote" "Could not post release to GitHub."
+
+            release_text=$(compose_release_text "$version" "$prev_ver")
+            post_release "$version" "$branch" "$user" "$repo" "$token" "$prerelease" "$release_text" ||
+            delete_remote_tag "$version" "$remote" "Could not post release to GitHub."
+            say "Draft release created successful. Go to https://github.com/"$user"/"$repo"/releases to check it out!"
+    fi
+fi
+}
+
+# Create a tag for the specified release.
+# The tag text will be composed from the changelog contents enclosed between the
+# specified release number and the previous one.
+create_local_tag() {
+    version="$1"
+    prev_ver="$2"
 
     # Create tag.
-    tag_text=$(compose_tag_text "$prev_version" "$version")
-    say "Preparing to create tag..."
-    say "Tag: v$version"
-    say "Tag text:"
+    say "Obtaining tag description for local tag v$version..."
+    tag_text=$(compose_tag_text "$version" "$prev_ver") || die "Could not compose tag description."
+    say "Tag description for v$version:"
     echo "$tag_text"
     say "Continue with tag creation?"
-    get_user_confirmation || die "Tag not created."
+    get_user_confirmation || die "Local v$version not created."
 
-    git tag -a "v$version" -m "$tag_text"
-    ok_or_die "Tag v$version not created."
-    say "Tag v$version created."
+    git tag -a v"$version" -m "$tag_text"
+    ok_or_die "Local tag v$version not created."
+    say "Local tag v$version created."
+}
+
+delete_local_tag() {
+    version="$1"
+    err_msg="$2"
+    say "Reverting local tag created by us..."
+    git tag -d v"$version"
+    die "$2"
+}
+
+delete_remote_tag() {
+    version="$1"
+    remote="$2"
+    say "Reverting remote tag created by us..."
+    git push --delete "$remote" v"$version"
+    delete_local_tag "$1" "$3"
+}
+
+push_local_tag() {
+    version="$1"
+    remote="$2"
+    say "Pushing local tag v$version to $remote..."
+    git push "$remote" v"$version"
 }
 
 # Check if able to run firecracker.
