[devtool] copy relase artifacts before test run
Signed-off-by: Luminita Voicu <lumivo@amazon.com>

diff --git a/tools/devtool b/tools/devtool
--- a/tools/devtool
+++ b/tools/devtool
@@ -997,8 +997,8 @@ cmd_build_release_archive() {
     say "Will start preparing release archive for v$version ..."
     get_user_confirmation || die "Aborted."
 
-    # Run tests, build release binaries and strip them from debug symbols.
-    ( cmd_build --release && cmd_strip && cmd_test ) || die "Aborted."
+    # Build release binaries and strip them from debug symbols.
+    ( cmd_build --release && cmd_strip ) || die "Aborted."
 
     release_suffix="v$version-$(uname -m)"
     release_dir="release-$release_suffix"
@@ -1015,17 +1015,28 @@ cmd_build_release_archive() {
     done
 
     add_swagger_artifact "$release_dir"
-    add_folder_artifact "$release_dir" "test_results" "$release_suffix"
     add_file_artifact "$release_dir" "$seccomp_json" "seccomp-filter-$release_suffix.json"
     for file in "LICENSE" "NOTICE" "THIRD-PARTY"; do
         add_file_artifact "$release_dir" "$file"
     done
+
+    # Run tests to obtain test reports dir.
+    cmd_test || cleanup_release_dir "$release_dir" "Tests failed."
+    add_folder_artifact "$release_dir" "test_results" "$release_suffix"
 
     # Create release archive.
     archive_name="firecracker-$release_suffix.tgz"
     say "Creating release archive..."
     tar -czf "$archive_name" "$release_dir"
     say "Done. Archive $archive_name successfully created."
+}
+
+cleanup_release_dir() {
+    release_dir="$1"
+    error_msg="$2"
+
+    rm -rf "$release_dir"
+    die "$error_msg"
 }
 
 check_file_existence() {
